import { Poppins } from 'next/font/google'
import '@ui/globals.css';
import Providers from '@context/Providers';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "600", "900"],
  display: 'swap'
})

export const metadata = {
  title: 'Herencia App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
