import {  Poppins, Inter } from 'next/font/google'
import './ui/globals.css';
import { SidebarProvider } from '@/context/SidebarContext';

const poppins = Poppins({ 
  subsets: ['latin'] , 
  weight: ["100", "200", "300", "600",  "900"]})

export const metadata = {
  title: 'Herencia App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SidebarProvider>
          {children}
        </SidebarProvider>
      </body>
    </html>
  )
}
